% This script shows (in 10 ms buckets) the average behaviour a hoverfly
% displays for any given stimuli

% Stimuli to choose from, select any
% stimuli = ["Dorsal_Loom_Fast", "Dorsal_Loom_HalfFast", ...
%           "Dorsal_Loom_Halfslow", "Dorsal_Loom_Slow", ...
%           "Ventral_Loom_Fast", "Ventral_Loom_HalfFast", ...
%           "Ventral_Loom_HalfSlow", "Ventral_Loom_Slow", ...
%           "Dorsal_Loom_control", "Ventral_Loom_control"];

